name: Test

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: [self-hosted, linux, x64, client4]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Rebuild and run an image
        run: |
          docker-compose down client_test server
          docker system prune -af
          docker-compose up -d --build client_test server
